name: Run Shell Script

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual triggering from GitHub UI
    inputs:
      resumeUrl:
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x ./main.sh

      - name: Run script
        run: |
          result=$(./main.sh | sed 's/"/\"/g')
          echo "{"result": "$result"}" | curl -X POST "${{ inputs.resumeUrl }}" -H "Content-Type: application/json" --data @-

