
name: Run Shell Script

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual triggering from GitHub UI
    inputs:
      resumeUrl:
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x ./main.sh

      - name: Run script
        run: ./main.sh | curl -X POST ${{ inputs.resumeUrl }} --data @-
